version: 2

updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: friday
  rebase-strategy: disabled
  labels:
  - dependencies
  - gha

- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
    day: friday
  rebase-strategy: disabled
  labels:
  - dependencies
  - golang
